# yes, I am putting my compose file in my source repository. Fight me!
version: "3.8"
services:
  epsonkiosk: 
    privileged: true
    build: https://github.com/ogrady/epsonkiosk.git
    volumes:
    - type: bind
      source: ./scans/
      target: /app/node/scans/
    - type: bind
      source: ./config/
      target: /app/node/config/
    restart: always
    ports:
      - 3003:8080
    environment:
        HTTP_PORT: 8080
        WS_PORT: 8081